#!/usr/bin/env python3
"""Stage12 target-only de-novo multistate training.

This script reuses the Stage11 loss machinery but changes the scientific
contract: the model input is target-only. Source/pose initialization is removed
before corruption and `de_novo_multistate_mode=True` is set, so both bb_ca and
local_latents are generated by full product-space flow.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any

import torch

REPO = Path(__file__).resolve().parents[2]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))
if str(REPO / "src") not in sys.path:
    sys.path.insert(0, str(REPO / "src"))

import scripts.strategy01.stage04_real_complex_loss_debug as s4  # noqa: E402
import scripts.strategy01.stage05_extract_ae_latents as s5ae  # noqa: E402
import scripts.strategy01.stage10_pose_init_training as s10  # noqa: E402
import scripts.strategy01.stage11_flow_sequence_training as s11  # noqa: E402

DEFAULT_DATASET = REPO / "data/strategy01/stage10_exactaug_training/stage10_exactaug_trainval.pt"
DEFAULT_INIT_CKPT = REPO / "ckpts/stage10_pose_init_exactaug/runs/stage10_pose_init_exactaug_full_v2/mini_final.pt"
DEFAULT_AE_CKPT = REPO / "ckpts/stage03_multistate_loss/complexa_ae_init_readonly_copy.ckpt"
REPORT_DIR = REPO / "reports/strategy01/probes"
RUNS_DIR = REPO / "ckpts/stage12_de_novo_multistate/runs"

FORBIDDEN_MODEL_INPUT_KEYS = [
    "init_bb_ca_states",
    "source_bb_ca_states",
    "source_complex_paths",
    "source_interface_contact_labels",
    "source_interface_distance_labels",
]


def write_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(s4.jsonable(obj), ensure_ascii=False, indent=2), encoding="utf-8")


def choose_device(requested: str) -> torch.device:
    if requested == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if requested == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA requested but unavailable")
    return torch.device(requested)


def configure_stage12_loss(fm: Any, args: argparse.Namespace) -> dict[str, float]:
    cfg = fm.cfg_exp.loss.multistate
    from omegaconf import OmegaConf

    OmegaConf.set_struct(cfg, False)
    values = {
        "de_novo_multistate": True,
        "target_center_noise_scale_nm": args.target_center_noise_scale_nm,
        "latent_state_residual_noise_scale": args.latent_state_residual_noise_scale,
        "lambda_ae_seq": args.lambda_ae_seq,
        "lambda_seq_ae_consistency": args.lambda_seq_ae_consistency,
        "lambda_flow_gate_reg": args.lambda_flow_gate_reg,
        "ae_seq_cvar_topk": 2,
        "ae_seq_hard_state_alpha": args.ae_seq_hard_state_alpha,
        "ae_seq_hard_state_gamma": args.ae_seq_hard_state_gamma,
    }
    for key, value in values.items():
        cfg[key] = value
    return values


def make_de_novo_batch(batch: dict[str, Any]) -> dict[str, Any]:
    work = s4.clone_batch(batch)
    for key in FORBIDDEN_MODEL_INPUT_KEYS:
        work.pop(key, None)
    work["de_novo_multistate_mode"] = True
    return work


def forward_loss_stage12(
    model: torch.nn.Module,
    ae: torch.nn.Module,
    fm: Any,
    samples: list[dict[str, Any]],
    device: torch.device,
    seed: int | None = None,
) -> tuple[torch.Tensor, dict[str, torch.Tensor], dict[str, torch.Tensor], dict[str, Any]]:
    if seed is not None:
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)
    batch = s10.collate_variable(samples, device)
    work_batch = make_de_novo_batch(batch)
    work_batch = fm.corrupt_multistate_batch(work_batch)
    nn_out = model(work_batch)
    nn_out = s11.attach_ae_sequence_logits(ae, fm, work_batch, nn_out, ca_source="pred")
    losses = fm.compute_multistate_loss(work_batch, nn_out)
    return losses["multistate_total"].mean(), losses, nn_out, work_batch


def identity_metrics(nn_out: dict[str, torch.Tensor], batch: dict[str, Any]) -> dict[str, float]:
    target = batch["binder_seq_shared"]
    mask = batch["binder_seq_mask"]
    shared_id = s11.sequence_identity_from_logits(nn_out["seq_logits_shared"], target, mask)
    ae_state_id = s11.sequence_identity_from_logits(
        nn_out["ae_seq_logits_states"],
        target[:, None, :].expand_as(nn_out["ae_seq_logits_states"][..., 0]),
        batch["state_mask"],
    )
    return {
        "shared_identity_mean": float(shared_id.detach().mean().cpu().item()),
        "ae_state_identity_mean": float(ae_state_id.detach().mean().cpu().item()),
    }


def set_trainable(model: torch.nn.Module, phase: str) -> dict[str, Any]:
    return s11.set_trainable_stage11(model, "overfit" if phase == "overfit" else "mini")


def run_loop(
    model: torch.nn.Module,
    ae: torch.nn.Module,
    fm: Any,
    samples: list[dict[str, Any]],
    device: torch.device,
    phase: str,
    steps: int,
    batch_size: int,
    lr: float,
    eval_every: int,
) -> dict[str, Any]:
    model.train()
    trainable = set_trainable(model, phase)
    opt = torch.optim.AdamW([p for p in model.parameters() if p.requires_grad], lr=lr, weight_decay=0.01)
    fixed_subset = samples[: min(batch_size, len(samples))]
    started = time.time()
    with torch.no_grad():
        initial, initial_losses, initial_out, initial_batch = forward_loss_stage12(model, ae, fm, fixed_subset, device, seed=1207)
    history = []
    for step in range(1, steps + 1):
        subset = [samples[((step - 1) * batch_size + i) % len(samples)] for i in range(batch_size)]
        opt.zero_grad(set_to_none=True)
        total, losses, _, _ = forward_loss_stage12(model, ae, fm, subset, device, seed=step * 977)
        if not torch.isfinite(total):
            raise FloatingPointError(f"non-finite Stage12 loss at step {step}: {total}")
        total.backward()
        torch.nn.utils.clip_grad_norm_([p for p in model.parameters() if p.requires_grad], 1.0)
        opt.step()
        if step == 1 or step % eval_every == 0 or step == steps:
            with torch.no_grad():
                ev_total, ev_losses, ev_out, ev_batch = forward_loss_stage12(model, ae, fm, fixed_subset, device, seed=1207)
            row = {
                "step": step,
                "train_total": float(total.detach().cpu().item()),
                "eval_total": float(ev_total.detach().cpu().item()),
                "train_losses": s4.summarize_losses(losses),
                "eval_losses": s4.summarize_losses(ev_losses),
                "identity": identity_metrics(ev_out, ev_batch),
                "cuda_max_mem_gb": torch.cuda.max_memory_allocated() / (1024**3) if device.type == "cuda" else 0.0,
                "elapsed_sec": time.time() - started,
            }
            print(json.dumps({"phase": phase, **row}, ensure_ascii=False), flush=True)
            history.append(row)
    with torch.no_grad():
        final, final_losses, final_out, final_batch = forward_loss_stage12(model, ae, fm, fixed_subset, device, seed=1207)
    initial_value = float(initial.detach().cpu().item())
    final_value = float(final.detach().cpu().item())
    return {
        "phase": phase,
        "steps": steps,
        "batch_size": batch_size,
        "initial_total": initial_value,
        "final_total": final_value,
        "drop_fraction": (initial_value - final_value) / max(abs(initial_value), 1e-8),
        "initial_losses": s4.summarize_losses(initial_losses),
        "final_losses": s4.summarize_losses(final_losses),
        "initial_identity": identity_metrics(initial_out, initial_batch),
        "final_identity": identity_metrics(final_out, final_batch),
        "history": history,
        "trainable": trainable,
        "elapsed_sec": time.time() - started,
        "step_time_sec": (time.time() - started) / max(steps, 1),
        "cuda_max_mem_gb": torch.cuda.max_memory_allocated() / (1024**3) if device.type == "cuda" else 0.0,
    }


def build_model_stack(device: torch.device, args: argparse.Namespace):
    model, fm, model_meta = s4.build_model(device)
    ckpt_meta = s11.load_strategy_checkpoint(model, args.init_ckpt)
    loss_cfg = configure_stage12_loss(fm, args)
    ae = s5ae.load_autoencoder(args.ae_ckpt, device)
    for p in ae.parameters():
        p.requires_grad = False
    ae.eval()
    return model, fm, ae, model_meta, ckpt_meta, loss_cfg


def parse_args():
    parser = argparse.ArgumentParser(description="Stage12 target-only de-novo multistate training")
    parser.add_argument("--dataset", type=Path, default=DEFAULT_DATASET)
    parser.add_argument("--init-ckpt", type=Path, default=DEFAULT_INIT_CKPT)
    parser.add_argument("--ae-ckpt", type=Path, default=DEFAULT_AE_CKPT)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--run-name", default="stage12_de_novo_multistate")
    parser.add_argument("--seed", type=int, default=1207)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--max-train-samples", type=int, default=161)
    parser.add_argument("--max-val-samples", type=int, default=36)
    parser.add_argument("--overfit1-steps", type=int, default=80)
    parser.add_argument("--overfit4-steps", type=int, default=120)
    parser.add_argument("--pilot-steps", type=int, default=200)
    parser.add_argument("--eval-every", type=int, default=40)
    parser.add_argument("--lambda-ae-seq", type=float, default=1.5)
    parser.add_argument("--lambda-seq-ae-consistency", type=float, default=0.15)
    parser.add_argument("--lambda-flow-gate-reg", type=float, default=0.03)
    parser.add_argument("--ae-seq-hard-state-alpha", type=float, default=0.0)
    parser.add_argument("--ae-seq-hard-state-gamma", type=float, default=0.0)
    parser.add_argument("--target-center-noise-scale-nm", type=float, default=0.20)
    parser.add_argument("--latent-state-residual-noise-scale", type=float, default=0.05)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--skip-training", action="store_true")
    return parser.parse_args()


def main():
    args = parse_args()
    s4.set_seed(args.seed)
    device = choose_device(args.device)
    samples, manifest = s10.load_dataset(args.dataset)
    train_samples = [s for s in samples if s.get("split") == "train"][: args.max_train_samples]
    val_samples = [s for s in samples if s.get("split") == "val"][: args.max_val_samples]
    if not train_samples:
        raise RuntimeError("No Stage12 train samples selected")
    report_path = REPORT_DIR / f"{args.run_name}_results.json"
    run_dir = RUNS_DIR / args.run_name
    result: dict[str, Any] = {
        "status": "dry_run_passed" if args.dry_run else "running",
        "run_name": args.run_name,
        "device": str(device),
        "dataset": str(args.dataset),
        "train_count": len(train_samples),
        "val_count": len(val_samples),
        "contract": {
            "de_novo_multistate_mode": True,
            "forbidden_model_input_keys": FORBIDDEN_MODEL_INPUT_KEYS,
            "true_binder_sequence_allowed_only_as_loss_label": True,
            "bb_ca_flow_enabled": True,
            "local_latents_flow_enabled": True,
        },
        "manifest_summary": {k: v for k, v in manifest.items() if k != "samples"},
        "training": {},
    }
    if args.dry_run:
        write_json(report_path, result)
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return
    model, fm, ae, model_meta, ckpt_meta, loss_cfg = build_model_stack(device, args)
    result.update({"model_meta": model_meta, "init_ckpt_meta": ckpt_meta, "stage12_loss_cfg": loss_cfg})
    with torch.no_grad():
        probe_total, probe_losses, probe_out, probe_batch = forward_loss_stage12(model, ae, fm, train_samples[: min(2, len(train_samples))], device)
    result["probes"] = {
        "initial_total": float(probe_total.detach().cpu().item()),
        "losses": s4.summarize_losses(probe_losses),
        "identity": identity_metrics(probe_out, probe_batch),
    }
    write_json(report_path, result)
    if not args.skip_training:
        result["training"]["overfit1"] = run_loop(model, ae, fm, train_samples[:1], device, "overfit", args.overfit1_steps, 1, 2e-4, args.eval_every)
        model, fm, ae, _, _, _ = build_model_stack(device, args)
        result["training"]["overfit4"] = run_loop(model, ae, fm, train_samples[: min(4, len(train_samples))], device, "overfit", args.overfit4_steps, min(4, args.batch_size), 1e-4, args.eval_every)
        model, fm, ae, _, _, _ = build_model_stack(device, args)
        batch_size = min(args.batch_size, len(train_samples))
        try:
            result["training"]["pilot"] = run_loop(model, ae, fm, train_samples, device, "pilot", args.pilot_steps, batch_size, 5e-5, args.eval_every)
        except RuntimeError as exc:
            if "out of memory" not in str(exc).lower() or batch_size <= 1:
                raise
            torch.cuda.empty_cache()
            batch_size = 2 if batch_size > 2 else 1
            result.setdefault("fallbacks", []).append({"reason": "oom", "retry_batch_size": batch_size})
            model, fm, ae, _, _, _ = build_model_stack(device, args)
            result["training"]["pilot"] = run_loop(model, ae, fm, train_samples, device, "pilot", args.pilot_steps, batch_size, 5e-5, args.eval_every)
        run_dir.mkdir(parents=True, exist_ok=True)
        ckpt_path = run_dir / "stage12_pilot_final.pt"
        torch.save({"model_state_dict": model.state_dict(), "args": vars(args), "run_name": args.run_name}, ckpt_path)
        result["checkpoint_path"] = str(ckpt_path)
        if val_samples:
            with torch.no_grad():
                val_total, val_losses, val_out, val_batch = forward_loss_stage12(model, ae, fm, val_samples[: min(batch_size, len(val_samples))], device, seed=888)
            result["validation"] = {
                "total": float(val_total.detach().cpu().item()),
                "losses": s4.summarize_losses(val_losses),
                "identity": identity_metrics(val_out, val_batch),
            }
    result["status"] = "passed"
    write_json(report_path, result)
    print(json.dumps({"status": "passed", "report": str(report_path)}, ensure_ascii=False, indent=2), flush=True)


if __name__ == "__main__":
    main()
