#!/usr/bin/env python3
"""Stage12 target-only de-novo multistate training.

This script reuses the Stage11 loss machinery but changes the scientific
contract: the model input is target-only. Source/pose initialization is removed
before corruption and `de_novo_multistate_mode=True` is set, so both bb_ca and
local_latents are generated by full product-space flow.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any

import torch

REPO = Path(__file__).resolve().parents[2]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))
if str(REPO / "src") not in sys.path:
    sys.path.insert(0, str(REPO / "src"))

import scripts.strategy01.stage04_real_complex_loss_debug as s4  # noqa: E402
import scripts.strategy01.stage05_extract_ae_latents as s5ae  # noqa: E402
import scripts.strategy01.stage10_pose_init_training as s10  # noqa: E402
import scripts.strategy01.stage11_flow_sequence_training as s11  # noqa: E402

DEFAULT_DATASET = REPO / "data/strategy01/stage10_exactaug_training/stage10_exactaug_trainval.pt"
DEFAULT_INIT_CKPT = REPO / "ckpts/stage10_pose_init_exactaug/runs/stage10_pose_init_exactaug_full_v2/mini_final.pt"
DEFAULT_AE_CKPT = REPO / "ckpts/complexa_ae.ckpt"
DEFAULT_SAMPLING_CONFIG = REPO / "configs/pipeline/model_sampling.yaml"
REPORT_DIR = REPO / "reports/strategy01/probes"
RUNS_DIR = REPO / "ckpts/stage12_de_novo_multistate/runs"

FORBIDDEN_MODEL_INPUT_KEYS = [
    "init_bb_ca_states",
    "source_bb_ca_states",
    "source_complex_paths",
    "source_interface_contact_labels",
    "source_interface_distance_labels",
]


def write_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(s4.jsonable(obj), ensure_ascii=False, indent=2), encoding="utf-8")


def tensor_tree_to_device(obj: Any, device: torch.device) -> Any:
    if torch.is_tensor(obj):
        return obj.to(device=device)
    if isinstance(obj, dict):
        return {key: tensor_tree_to_device(value, device) for key, value in obj.items()}
    if isinstance(obj, list):
        return [tensor_tree_to_device(value, device) for value in obj]
    if isinstance(obj, tuple):
        return tuple(tensor_tree_to_device(value, device) for value in obj)
    return obj


def detach_tensor_tree_to_cpu(obj: Any) -> Any:
    if torch.is_tensor(obj):
        return obj.detach().cpu()
    if isinstance(obj, dict):
        return {key: detach_tensor_tree_to_cpu(value) for key, value in obj.items()}
    if isinstance(obj, list):
        return [detach_tensor_tree_to_cpu(value) for value in obj]
    if isinstance(obj, tuple):
        return tuple(detach_tensor_tree_to_cpu(value) for value in obj)
    return obj


def choose_device(requested: str) -> torch.device:
    if requested == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if requested == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA requested but unavailable")
    return torch.device(requested)


def configure_stage12_loss(fm: Any, args: argparse.Namespace) -> dict[str, float]:
    cfg = fm.cfg_exp.loss.multistate
    from omegaconf import OmegaConf

    OmegaConf.set_struct(cfg, False)
    values = {
        "de_novo_multistate": True,
        "target_center_noise_scale_nm": args.target_center_noise_scale_nm,
        "latent_state_residual_noise_scale": args.latent_state_residual_noise_scale,
        "lambda_ae_seq": args.lambda_ae_seq,
        "lambda_seq_ae_consistency": args.lambda_seq_ae_consistency,
        "lambda_flow_gate_reg": args.lambda_flow_gate_reg,
        "ae_seq_cvar_topk": 2,
        "ae_seq_hard_state_alpha": args.ae_seq_hard_state_alpha,
        "ae_seq_hard_state_gamma": args.ae_seq_hard_state_gamma,
    }
    for key, value in values.items():
        cfg[key] = value
    return values


def make_de_novo_batch(
    batch: dict[str, Any],
    stage13_native_state_path: bool = False,
    stage14_enable_bounded_latent_repair: bool = False,
    stage14_latent_repair_max_norm: float = 0.25,
) -> dict[str, Any]:
    work = s4.clone_batch(batch)
    for key in FORBIDDEN_MODEL_INPUT_KEYS:
        work.pop(key, None)
    if bool(work.get("use_ca_coors_nm_feature", False)):
        raise ValueError("de_novo_multistate forbids real optional CA coordinate features")
    if bool(work.get("use_residue_type_feature", False)):
        raise ValueError("de_novo_multistate forbids real optional residue-type features")
    work["de_novo_multistate_mode"] = True
    if stage13_native_state_path:
        work["stage13_native_state_path"] = True
    if stage14_enable_bounded_latent_repair:
        work["stage14_enable_bounded_latent_repair"] = True
        work["stage14_latent_repair_max_norm"] = float(stage14_latent_repair_max_norm)
    return work


def normalize_state_weights(batch: dict[str, Any], device: torch.device) -> torch.Tensor:
    present = batch["state_present_mask"].to(device=device).bool()
    weights = batch.get("target_state_weights")
    if weights is None:
        weights = torch.ones_like(present, dtype=torch.float32, device=device)
    else:
        weights = weights.to(device=device, dtype=torch.float32)
    weights = weights * present.float()
    denom = weights.sum(dim=1, keepdim=True)
    fallback = present.float() / present.float().sum(dim=1, keepdim=True).clamp_min(1.0)
    return torch.where(denom > 1e-8, weights / denom.clamp_min(1e-8), fallback)


def weighted_average_states(states: dict[str, torch.Tensor], weights: torch.Tensor) -> dict[str, torch.Tensor]:
    return {dm: torch.sum(value * weights[:, :, None, None].to(dtype=value.dtype), dim=1) for dm, value in states.items()}


def load_sampling_cfg(path: Path) -> dict[str, Any]:
    from omegaconf import OmegaConf as _OmegaConf

    return _OmegaConf.to_container(_OmegaConf.load(path).model, resolve=True)


def add_weighted_legacy_fields(batch: dict[str, Any], weights: torch.Tensor) -> None:
    batch["x_1"] = weighted_average_states(batch["x_1_states"], weights)
    batch["x_0"] = weighted_average_states(batch["x_0_states"], weights)
    batch["x_t"] = weighted_average_states(batch["x_t_states"], weights)
    batch["t"] = {dm: torch.sum(batch["t_states"][dm] * weights, dim=1) for dm in batch["t_states"]}
    if "x_sc_states" in batch:
        batch["x_sc"] = weighted_average_states(batch["x_sc_states"], weights)
    else:
        batch["x_sc"] = {dm: torch.zeros_like(batch["x_t"][dm]) for dm in batch["x_t"]}


def attach_teacher_forced_self_conditioning(
    model: torch.nn.Module,
    fm: Any,
    batch: dict[str, Any],
    weights: torch.Tensor,
) -> dict[str, float]:
    """Attach model-generated clean predictions as x_sc_states on a teacher-forced interpolant.

    This mirrors original Complexa sampling self-conditioning without leaking clean
    binder geometry: x_sc_states are generated by the current model from the same
    noisy x_t_states and target-only conditioning, with gradients stopped.
    """
    batch.pop("x_sc_states", None)
    add_weighted_legacy_fields(batch, weights)
    state_mask = batch["state_mask"].bool()
    b, k, n = state_mask.shape
    with torch.no_grad():
        nn_sc = model(batch)
        x_sc_states: dict[str, torch.Tensor] = {}
        diagnostics: dict[str, float] = {}
        for dm in fm.data_modes:
            x_t = batch["x_t_states"][dm]
            flat_x = x_t.reshape(b * k, n, x_t.shape[-1])
            flat_mask = state_mask.reshape(b * k, n)
            flat_t = batch["t_states"][dm].reshape(b * k)
            param = fm.cfg_exp.nn.output_parameterization[dm]
            flat_nn = {param: nn_sc[f"{dm}_states"].reshape(b * k, n, x_t.shape[-1])}
            base = fm.base_flow_matchers[dm]
            flat_nn = base.nn_out_add_clean_sample_prediction(flat_x, flat_t, flat_mask, flat_nn)
            clean = flat_nn["x_1"].reshape(b, k, n, x_t.shape[-1]).detach() * state_mask[..., None]
            x_sc_states[dm] = clean
            diagnostics[f"teacher_self_cond_{dm}_mean_abs"] = float(clean.abs().mean().detach().cpu().item())
        batch["x_sc_states"] = x_sc_states
    add_weighted_legacy_fields(batch, weights)
    batch["stage15_teacher_self_conditioned"] = True
    return diagnostics


def target_anchor_center(batch: dict[str, Any], device: torch.device) -> torch.Tensor | None:
    """Return target-state anchor centers using hotspot residues when present.

    The center is target-only information.  It is allowed in de-novo mode and is
    used only to prevent global bb_ca translation runaway during rollout/replay.
    """
    x_target = batch.get("x_target_states")
    target_mask = batch.get("target_mask_states")
    if x_target is None or target_mask is None:
        return None
    ca = x_target.to(device=device)[..., 1, :]
    ca_mask = target_mask.to(device=device).bool()[..., 1]
    hotspot = batch.get("target_hotspot_mask_states")
    if hotspot is not None:
        hotspot_mask = hotspot.to(device=device).bool() & ca_mask
        use_mask = torch.where(hotspot_mask.any(dim=-1, keepdim=True), hotspot_mask, ca_mask)
    else:
        use_mask = ca_mask
    denom = use_mask.float().sum(dim=2, keepdim=True).clamp_min(1.0)
    return (ca * use_mask[..., None].float()).sum(dim=2) / denom


def project_bb_ca_to_target_shell(
    batch: dict[str, Any],
    bb_ca: torch.Tensor,
    state_mask: torch.Tensor,
    max_center_distance_nm: float,
) -> tuple[torch.Tensor, dict[str, float]]:
    """Bound global binder translation without using clean binder pose.

    This moves each state-specific binder as a rigid translation only when its
    center is farther than the target/hotspot shell.  Internal binder geometry is
    unchanged; the projection is target-only and therefore compatible with the
    Stage12 de-novo contract.
    """
    if max_center_distance_nm <= 0.0:
        return bb_ca, {"enabled": False}
    centers = target_anchor_center(batch, bb_ca.device)
    if centers is None:
        return bb_ca, {"enabled": False, "reason": "missing_target_states"}
    mask = state_mask.to(device=bb_ca.device).bool()
    binder_center = (bb_ca * mask[..., None].float()).sum(dim=2) / mask.float().sum(dim=2, keepdim=True).clamp_min(1.0)
    vec = binder_center - centers
    dist = vec.norm(dim=-1).clamp_min(1e-6)
    scale = (float(max_center_distance_nm) / dist).clamp(max=1.0)
    projected_center = centers + vec * scale[..., None]
    shift = (projected_center - binder_center)[:, :, None, :]
    projected = (bb_ca + shift) * mask[..., None].float()
    moved = (dist > float(max_center_distance_nm)) & batch["state_present_mask"].to(device=bb_ca.device).bool()
    return projected, {
        "enabled": True,
        "max_center_distance_nm": float(max_center_distance_nm),
        "pre_center_distance_mean_nm": float(dist[batch["state_present_mask"].to(device=bb_ca.device).bool()].mean().detach().cpu().item()),
        "moved_fraction": float(moved.float().mean().detach().cpu().item()),
    }


def build_replay_condition_batch(
    model: torch.nn.Module,
    fm: Any,
    batch: dict[str, Any],
    device: torch.device,
    sampling_cfg: dict[str, Any],
    rollout_steps: int,
    collect_fraction: float,
    max_loss_t: float,
    teacher_blend: float = 0.0,
    safe_max_bb_ca_distance_nm: float = 0.0,
    safe_max_local_latents_distance: float = 0.0,
    safe_fallback_max_blend: float = 0.85,
    target_shell_max_center_distance_nm: float = 0.0,
    stage13_native_state_path: bool = False,
    stage14_enable_bounded_latent_repair: bool = False,
    stage14_latent_repair_max_norm: float = 0.25,
    seed: int | None = None,
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Generate a target-only short rollout and return its intermediate state as a training condition."""
    if seed is not None:
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)
    work = make_de_novo_batch(
        batch,
        stage13_native_state_path=stage13_native_state_path,
        stage14_enable_bounded_latent_repair=stage14_enable_bounded_latent_repair,
        stage14_latent_repair_max_norm=stage14_latent_repair_max_norm,
    )
    work = fm.corrupt_multistate_batch(work)
    state_mask = work["state_mask"].to(device=device).bool()
    b, k, n = state_mask.shape
    weights = normalize_state_weights(work, device)
    x_states = {dm: value.detach().clone() for dm, value in work["x_0_states"].items()}
    x_start = {dm: value.detach().clone() for dm, value in x_states.items()}
    rollout_steps = max(2, int(rollout_steps))
    collect_step = int(round(float(collect_fraction) * rollout_steps))
    collect_step = min(max(1, collect_step), rollout_steps - 1)
    ts, gt = fm.sample_schedule(nsteps=rollout_steps, sampling_model_args=sampling_cfg)
    ts = {dm: value.to(device) for dm, value in ts.items()}
    gt = {dm: value.to(device) for dm, value in gt.items()}
    was_training = model.training
    model.eval()
    x_sc_states: dict[str, torch.Tensor] | None = None
    with torch.no_grad():
        for step in range(collect_step):
            work["x_t_states"] = {dm: value.detach() for dm, value in x_states.items()}
            work["t_states"] = {dm: ts[dm][step].expand(b, k).to(device) for dm in fm.data_modes}
            if x_sc_states is not None:
                work["x_sc_states"] = {dm: value.detach() for dm, value in x_sc_states.items()}
            else:
                work.pop("x_sc_states", None)
            if stage13_native_state_path:
                work["stage13_native_state_path"] = True
            add_weighted_legacy_fields(work, weights)
            work["de_novo_multistate_mode"] = True
            nn_out = model(work)
            updated: dict[str, torch.Tensor] = {}
            next_x_sc_states: dict[str, torch.Tensor] = {}
            for dm in fm.data_modes:
                flat_x = x_states[dm].reshape(b * k, n, x_states[dm].shape[-1])
                flat_mask = state_mask.reshape(b * k, n)
                flat_t = ts[dm][step].expand(b * k).to(device)
                dt = ts[dm][step + 1] - ts[dm][step]
                param = fm.cfg_exp.nn.output_parameterization[dm]
                flat_nn = {param: nn_out[f"{dm}_states"].reshape(b * k, n, x_states[dm].shape[-1])}
                base = fm.base_flow_matchers[dm]
                flat_nn = base.nn_out_add_clean_sample_prediction(flat_x, flat_t, flat_mask, flat_nn)
                next_x_sc_states[dm] = flat_nn["x_1"].reshape(b, k, n, x_states[dm].shape[-1]).detach()
                flat_nn = base.nn_out_add_simulation_tensor(flat_x, flat_t, flat_mask, flat_nn)
                flat_nn = base.nn_out_add_guided_simulation_tensor(flat_nn, None, None, guidance_w=1.0, ag_ratio=0.0)
                flat_next = base.simulation_step(
                    x_t=flat_x,
                    nn_out=flat_nn,
                    t=flat_t,
                    dt=dt,
                    gt=gt[dm][step],
                    mask=flat_mask,
                    simulation_step_params=sampling_cfg[dm]["simulation_step_params"],
                )
                state_next = flat_next.reshape(b, k, n, x_states[dm].shape[-1]) * state_mask[..., None]
                if dm == "bb_ca" and target_shell_max_center_distance_nm > 0.0:
                    state_next, _ = project_bb_ca_to_target_shell(work, state_next, state_mask, target_shell_max_center_distance_nm)
                updated[dm] = state_next
            x_states = updated
            x_sc_states = next_x_sc_states
    model.train(was_training)
    raw_bb_distance = float((x_states["bb_ca"] - work["x_1_states"]["bb_ca"]).abs().mean().detach().cpu().item())
    raw_latent_distance = float((x_states["local_latents"] - work["x_1_states"]["local_latents"]).abs().mean().detach().cpu().item())
    teacher_blend = max(0.0, min(float(teacher_blend), 0.95))
    effective_teacher_blend = teacher_blend
    required_blends: list[float] = []
    if safe_max_bb_ca_distance_nm > 0.0 and raw_bb_distance > safe_max_bb_ca_distance_nm:
        required_blends.append(1.0 - safe_max_bb_ca_distance_nm / max(raw_bb_distance, 1e-6))
    if safe_max_local_latents_distance > 0.0 and raw_latent_distance > safe_max_local_latents_distance:
        required_blends.append(1.0 - safe_max_local_latents_distance / max(raw_latent_distance, 1e-6))
    if required_blends:
        safe_fallback_max_blend = max(0.0, min(float(safe_fallback_max_blend), 0.95))
        effective_teacher_blend = max(teacher_blend, min(max(required_blends), safe_fallback_max_blend))

    replay = make_de_novo_batch(
        batch,
        stage13_native_state_path=stage13_native_state_path,
        stage14_enable_bounded_latent_repair=stage14_enable_bounded_latent_repair,
        stage14_latent_repair_max_norm=stage14_latent_repair_max_norm,
    )
    replay["x_0_states"] = x_start
    if effective_teacher_blend > 0.0:
        replay["x_t_states"] = {
            dm: ((1.0 - effective_teacher_blend) * value + effective_teacher_blend * work["x_1_states"][dm]).detach()
            for dm, value in x_states.items()
        }
    else:
        replay["x_t_states"] = {dm: value.detach() for dm, value in x_states.items()}
    replay["t_states"] = {dm: ts[dm][collect_step].expand(b, k).to(device) for dm in fm.data_modes}
    if max_loss_t > 0.0:
        replay["t_states"] = {dm: torch.clamp(value, max=float(max_loss_t)) for dm, value in replay["t_states"].items()}
    replay["state_mask"] = state_mask
    replay["stage12_primary_state_tensors"] = True
    replay["stage12_replay_condition"] = True
    if x_sc_states is not None:
        replay["x_sc_states"] = {dm: value.detach() for dm, value in x_sc_states.items()}
    add_weighted_legacy_fields(replay, weights)
    diagnostics = {
        "rollout_steps": rollout_steps,
        "collect_step": collect_step,
        "collect_t_raw": {dm: float(ts[dm][collect_step].detach().cpu().item()) for dm in fm.data_modes},
        "collect_t_loss": {dm: float(replay["t_states"][dm][0, 0].detach().cpu().item()) for dm in fm.data_modes},
        "bb_ca_replay_delta_nm": float((replay["x_t_states"]["bb_ca"] - x_start["bb_ca"]).abs().mean().detach().cpu().item()),
        "local_latents_replay_delta": float((replay["x_t_states"]["local_latents"] - x_start["local_latents"]).abs().mean().detach().cpu().item()),
        "teacher_blend": teacher_blend,
        "effective_teacher_blend": effective_teacher_blend,
        "safe_replay_adjusted": bool(effective_teacher_blend > teacher_blend + 1e-6),
        "safe_max_bb_ca_distance_nm": float(safe_max_bb_ca_distance_nm),
        "safe_max_local_latents_distance": float(safe_max_local_latents_distance),
        "raw_bb_ca_distance_to_clean_nm": raw_bb_distance,
        "raw_local_latents_distance_to_clean": raw_latent_distance,
        "bb_ca_distance_to_clean_nm": float((replay["x_t_states"]["bb_ca"] - work["x_1_states"]["bb_ca"]).abs().mean().detach().cpu().item()),
        "local_latents_distance_to_clean": float((replay["x_t_states"]["local_latents"] - work["x_1_states"]["local_latents"]).abs().mean().detach().cpu().item()),
        "target_shell_max_center_distance_nm": float(target_shell_max_center_distance_nm),
        "stage13_native_state_path": bool(stage13_native_state_path),
    }
    return replay, diagnostics


def parse_replay_cache_levels(levels: str) -> list[tuple[str, float]]:
    parsed: list[tuple[str, float]] = []
    for item in str(levels).split(","):
        item = item.strip()
        if not item:
            continue
        if ":" in item:
            name, value = item.split(":", 1)
        else:
            name, value = f"level{len(parsed)}", item
        blend = max(0.0, min(float(value), 0.95))
        parsed.append((name.strip() or f"level{len(parsed)}", blend))
    if not parsed:
        parsed = [("medium", 0.35)]
    return parsed


def choose_replay_cache_level(args: argparse.Namespace, step: int, total_steps: int) -> str | None:
    levels = parse_replay_cache_levels(args.replay_cache_levels)
    if len(levels) == 1:
        return levels[0][0]
    switches = [float(x) for x in str(args.replay_curriculum_switches).split(",") if str(x).strip()]
    progress = step / max(float(total_steps), 1.0)
    idx = 0
    for switch in switches:
        if progress >= switch:
            idx += 1
    idx = min(idx, len(levels) - 1)
    return levels[idx][0]


def build_fixed_replay_cache(
    model: torch.nn.Module,
    fm: Any,
    samples: list[dict[str, Any]],
    device: torch.device,
    args: argparse.Namespace,
    sampling_cfg: dict[str, Any],
    batch_size: int,
    refresh_index: int = 0,
) -> dict[str, list[dict[str, Any]]]:
    """Precompute replay conditions so training sees a stable sampled distribution.

    Stage12C generated replay states online.  That proved the plumbing worked,
    but the replay distribution changed with the model and seed, making it hard
    to distinguish genuine latent-manifold improvement from rollout noise.
    Stage12D fixes a small cache per phase and schedules easy/medium/hard
    blends over it.
    """
    if not samples:
        return {}
    cache: dict[str, list[dict[str, Any]]] = {}
    levels = parse_replay_cache_levels(args.replay_cache_levels)
    nbatches = max(1, min(int(args.replay_cache_batches), (len(samples) + batch_size - 1) // max(batch_size, 1)))
    for level_name, blend in levels:
        cache[level_name] = []
        for batch_idx in range(nbatches):
            start = (batch_idx * batch_size) % len(samples)
            subset = [samples[(start + i) % len(samples)] for i in range(batch_size)]
            collated = s10.collate_variable(subset, device)
            replay_batch, diagnostics = build_replay_condition_batch(
                model,
                fm,
                collated,
                device,
                sampling_cfg,
                rollout_steps=args.replay_rollout_steps,
                collect_fraction=args.replay_collect_fraction,
                max_loss_t=args.replay_max_loss_t,
                teacher_blend=blend,
                safe_max_bb_ca_distance_nm=args.replay_safe_max_bb_ca_distance_nm,
                safe_max_local_latents_distance=args.replay_safe_max_local_latents_distance,
                safe_fallback_max_blend=args.replay_safe_fallback_max_blend,
                target_shell_max_center_distance_nm=args.replay_target_shell_max_center_distance_nm,
                stage13_native_state_path=bool(getattr(args, "stage13_native_state_path", False)),
                stage14_enable_bounded_latent_repair=bool(
                    getattr(args, "stage14_enable_bounded_latent_repair", False)
                ),
                stage14_latent_repair_max_norm=float(getattr(args, "stage14_latent_repair_max_norm", 0.25)),
                seed=9301 + refresh_index * 1000003 + batch_idx * 101 + int(blend * 1000),
            )
            cache[level_name].append(
                {
                    "batch": detach_tensor_tree_to_cpu(replay_batch),
                    "diagnostics": diagnostics,
                    "level": level_name,
                    "teacher_blend": blend,
                    "sample_indices": list(range(start, start + len(subset))),
                }
            )
    return cache


def forward_loss_stage12(
    model: torch.nn.Module,
    ae: torch.nn.Module,
    fm: Any,
    samples: list[dict[str, Any]],
    device: torch.device,
    args: argparse.Namespace | None = None,
    sampling_cfg: dict[str, Any] | None = None,
    replay: bool = False,
    seed: int | None = None,
    replay_cache_entry: dict[str, Any] | None = None,
) -> tuple[torch.Tensor, dict[str, torch.Tensor], dict[str, torch.Tensor], dict[str, Any]]:
    if seed is not None:
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)
    replay_diag: dict[str, Any] = {}
    if replay_cache_entry is not None:
        work_batch = tensor_tree_to_device(replay_cache_entry["batch"], device)
        replay_diag = dict(replay_cache_entry.get("diagnostics", {}))
        replay_diag["fixed_cache_level"] = replay_cache_entry.get("level")
        replay_diag["fixed_cache_teacher_blend"] = replay_cache_entry.get("teacher_blend")
        replay_diag["fixed_cache_sample_indices"] = replay_cache_entry.get("sample_indices")
    else:
        batch = s10.collate_variable(samples, device)
    if replay and replay_cache_entry is None:
        if args is None or sampling_cfg is None:
            raise ValueError("Stage12 replay requires args and sampling_cfg")
        work_batch, replay_diag = build_replay_condition_batch(
            model,
            fm,
            batch,
            device,
            sampling_cfg,
            rollout_steps=args.replay_rollout_steps,
            collect_fraction=args.replay_collect_fraction,
            max_loss_t=args.replay_max_loss_t,
            teacher_blend=args.replay_teacher_blend,
            safe_max_bb_ca_distance_nm=args.replay_safe_max_bb_ca_distance_nm,
            safe_max_local_latents_distance=args.replay_safe_max_local_latents_distance,
            safe_fallback_max_blend=args.replay_safe_fallback_max_blend,
            target_shell_max_center_distance_nm=args.replay_target_shell_max_center_distance_nm,
            stage13_native_state_path=bool(getattr(args, "stage13_native_state_path", False)),
            stage14_enable_bounded_latent_repair=bool(
                getattr(args, "stage14_enable_bounded_latent_repair", False)
            ),
            stage14_latent_repair_max_norm=float(getattr(args, "stage14_latent_repair_max_norm", 0.25)),
            seed=seed,
        )
    elif replay_cache_entry is None:
        work_batch = make_de_novo_batch(
            batch,
            stage13_native_state_path=bool(getattr(args, "stage13_native_state_path", False)),
            stage14_enable_bounded_latent_repair=bool(
                getattr(args, "stage14_enable_bounded_latent_repair", False)
            ),
            stage14_latent_repair_max_norm=float(getattr(args, "stage14_latent_repair_max_norm", 0.25)),
        )
        work_batch = fm.corrupt_multistate_batch(work_batch)
        if args is not None and bool(getattr(args, "enable_teacher_self_conditioning", False)):
            prob = max(0.0, min(float(getattr(args, "teacher_self_cond_prob", 1.0)), 1.0))
            draw = 0.0 if seed is None else ((int(seed) * 9973) % 10000) / 10000.0
            if draw < prob:
                weights = normalize_state_weights(work_batch, device)
                sc_diag = attach_teacher_forced_self_conditioning(model, fm, work_batch, weights)
                replay_diag.update(sc_diag)
                replay_diag["teacher_self_conditioned"] = True
            else:
                replay_diag["teacher_self_conditioned"] = False
    nn_out = model(work_batch)
    nn_out = s11.attach_ae_sequence_logits(ae, fm, work_batch, nn_out, ca_source="pred")
    losses = fm.compute_multistate_loss(work_batch, nn_out)
    total = losses["multistate_total"].mean()
    if replay and args is not None:
        base_total = total
        replay_extra = (
            float(args.replay_extra_ae_seq_weight) * losses["multistate_ae_seq_justlog"]
            + float(args.replay_extra_seq_ae_consistency_weight) * losses["multistate_seq_ae_consistency_justlog"]
            + float(args.replay_extra_contact_weight) * losses["multistate_contact_justlog"]
            + float(args.replay_extra_distance_weight) * losses["multistate_distance_justlog"]
            + float(args.replay_extra_clash_weight) * losses["multistate_clash_justlog"]
        )
        losses["stage12_replay_extra_justlog"] = replay_extra
        losses["stage12_replay_total_justlog"] = losses["multistate_total"] + replay_extra
        total = float(getattr(args, "replay_base_loss_scale", 1.0)) * base_total + replay_extra.mean()
        work_batch["stage12_replay_diagnostics"] = replay_diag
    if replay_diag:
        work_batch["stage15_teacher_self_conditioning_diagnostics"] = replay_diag
    return total, losses, nn_out, work_batch


def identity_metrics(nn_out: dict[str, torch.Tensor], batch: dict[str, Any]) -> dict[str, float]:
    target = batch["binder_seq_shared"]
    mask = batch["binder_seq_mask"]
    shared_id = s11.sequence_identity_from_logits(nn_out["seq_logits_shared"], target, mask)
    ae_state_id = s11.sequence_identity_from_logits(
        nn_out["ae_seq_logits_states"],
        target[:, None, :].expand_as(nn_out["ae_seq_logits_states"][..., 0]),
        batch["state_mask"],
    )
    return {
        "shared_identity_mean": float(shared_id.detach().mean().cpu().item()),
        "ae_state_identity_mean": float(ae_state_id.detach().mean().cpu().item()),
    }


def set_trainable(
    model: torch.nn.Module,
    phase: str,
    stage13_heads_only: bool = False,
    stage13_train_latent_repair: bool = False,
    stage14_train_bounded_latent_repair: bool = False,
    stage14_native_latent_warmup: bool = False,
) -> dict[str, Any]:
    if stage13_heads_only:
        for p in model.parameters():
            p.requires_grad = False
        prefixes = [
            "soft_sequence_feedback_projector",
            "cross_state_shared_seq_attention",
            "shared_seq_token_norm",
            "shared_seq_token_update",
            "shared_seq_to_state_projector",
            "shared_seq_token_head",
            "state_xt_bb_ca_projector",
            "state_xt_latent_projector",
            "shared_seq_head",
            "state_seq_head",
            "shared_seq_consensus_gate",
            "state_seq_condition_projector",
            "state_condition_projector",
            "state_token_norm",
            "interface_quality_head",
        ]
        if stage13_train_latent_repair:
            prefixes += [
                "latent_sequence_repair_projector",
                "latent_sequence_repair_gate",
                "local_latents_linear",
            ]
        if stage14_train_bounded_latent_repair:
            # Stage14 trains the bounded residual adapter only.  Do not unfreeze
            # the checkpoint-native local_latents_linear here: Stage13 showed
            # that moving the full native latent readout on tiny replay data
            # destabilizes the original Complexa prior.
            prefixes += [
                "latent_sequence_repair_projector",
                "latent_sequence_repair_gate",
                "soft_sequence_feedback_projector",
            ]
        if stage14_native_latent_warmup:
            # Stage14B: repair the actual sampled local-latent manifold rather
            # than only the final readout.  This keeps the pretrained native
            # target-concat generator mostly frozen, but lets the latent
            # velocity readout and top native transformer layers adapt to the
            # curated multistate/shared-sequence supervision.
            prefixes += [
                "local_latents_linear",
                "transformer_layers.10",
                "transformer_layers.11",
                "transformer_layers.12",
                "transformer_layers.13",
            ]
        for name, p in model.named_parameters():
            if any(name.startswith(prefix) for prefix in prefixes):
                p.requires_grad = True
        return {
            "phase": phase,
            "stage13_heads_only": True,
            "stage13_train_latent_repair": bool(stage13_train_latent_repair),
            "stage14_train_bounded_latent_repair": bool(stage14_train_bounded_latent_repair),
            "stage14_native_latent_warmup": bool(stage14_native_latent_warmup),
            "prefixes": prefixes,
            "trainable_params": sum(p.numel() for p in model.parameters() if p.requires_grad),
            "total_params": sum(p.numel() for p in model.parameters()),
        }
    return s11.set_trainable_stage11(model, "overfit" if phase == "overfit" else "mini")


def run_loop(
    model: torch.nn.Module,
    ae: torch.nn.Module,
    fm: Any,
    samples: list[dict[str, Any]],
    device: torch.device,
    phase: str,
    steps: int,
    batch_size: int,
    lr: float,
    eval_every: int,
    args: argparse.Namespace,
    sampling_cfg: dict[str, Any],
) -> dict[str, Any]:
    model.train()
    trainable = set_trainable(
        model,
        phase,
        stage13_heads_only=bool(getattr(args, "stage13_heads_only", False)),
        stage13_train_latent_repair=bool(getattr(args, "stage13_train_latent_repair", False)),
        stage14_train_bounded_latent_repair=bool(getattr(args, "stage14_enable_bounded_latent_repair", False)),
        stage14_native_latent_warmup=bool(getattr(args, "stage14_native_latent_warmup", False)),
    )
    opt = torch.optim.AdamW([p for p in model.parameters() if p.requires_grad], lr=lr, weight_decay=0.01)
    fixed_subset = samples[: min(batch_size, len(samples))]
    replay_cache: dict[str, list[dict[str, Any]]] = {}
    replay_cache_refresh_count = 0
    if args.enable_replay and args.enable_fixed_replay_cache:
        replay_cache = build_fixed_replay_cache(model, fm, samples, device, args, sampling_cfg, batch_size, replay_cache_refresh_count)
    started = time.time()
    with torch.no_grad():
        initial, initial_losses, initial_out, initial_batch = forward_loss_stage12(model, ae, fm, fixed_subset, device, args=args, sampling_cfg=sampling_cfg, seed=1207)
        replay_initial = None
        if args.enable_replay:
            replay_initial, replay_initial_losses, replay_initial_out, replay_initial_batch = forward_loss_stage12(
                model, ae, fm, fixed_subset, device, args=args, sampling_cfg=sampling_cfg, replay=True, seed=2207
            )
    history = []
    for step in range(1, steps + 1):
        subset = [samples[((step - 1) * batch_size + i) % len(samples)] for i in range(batch_size)]
        refresh_every = int(getattr(args, "replay_cache_refresh_every", 0) or 0)
        if (
            args.enable_replay
            and args.enable_fixed_replay_cache
            and refresh_every > 0
            and step > int(args.replay_warmup_steps)
            and (step - int(args.replay_warmup_steps)) % refresh_every == 0
        ):
            replay_cache_refresh_count += 1
            replay_cache = build_fixed_replay_cache(
                model,
                fm,
                samples,
                device,
                args,
                sampling_cfg,
                batch_size,
                replay_cache_refresh_count,
            )
        use_replay = bool(
            args.enable_replay
            and step > int(args.replay_warmup_steps)
            and ((step * 37) % 100) < int(100 * float(args.replay_mix_prob))
        )
        replay_cache_entry = None
        if use_replay and replay_cache:
            level = choose_replay_cache_level(args, step, steps)
            level_entries = replay_cache.get(level or "", [])
            if level_entries:
                replay_cache_entry = level_entries[(step // max(args.eval_every, 1)) % len(level_entries)]
        opt.zero_grad(set_to_none=True)
        total, losses, _, train_batch = forward_loss_stage12(
            model,
            ae,
            fm,
            subset,
            device,
            args=args,
            sampling_cfg=sampling_cfg,
            replay=use_replay,
            seed=step * 977,
            replay_cache_entry=replay_cache_entry,
        )
        if not torch.isfinite(total):
            raise FloatingPointError(f"non-finite Stage12 loss at step {step}: {total}")
        total.backward()
        torch.nn.utils.clip_grad_norm_([p for p in model.parameters() if p.requires_grad], 1.0)
        opt.step()
        if step == 1 or step % eval_every == 0 or step == steps:
            with torch.no_grad():
                ev_total, ev_losses, ev_out, ev_batch = forward_loss_stage12(model, ae, fm, fixed_subset, device, args=args, sampling_cfg=sampling_cfg, seed=1207)
                ev_replay_total = None
                ev_replay_identity = None
                ev_replay_diag = None
                if args.enable_replay:
                    eval_cache_entry = None
                    if replay_cache:
                        level = choose_replay_cache_level(args, step, steps)
                        entries = replay_cache.get(level or "", [])
                        if entries:
                            eval_cache_entry = entries[0]
                    ev_replay_total, ev_replay_losses, ev_replay_out, ev_replay_batch = forward_loss_stage12(
                        model,
                        ae,
                        fm,
                        fixed_subset,
                        device,
                        args=args,
                        sampling_cfg=sampling_cfg,
                        replay=True,
                        seed=2207,
                        replay_cache_entry=eval_cache_entry,
                    )
                    ev_replay_identity = identity_metrics(ev_replay_out, ev_replay_batch)
                    ev_replay_diag = ev_replay_batch.get("stage12_replay_diagnostics")
            row = {
                "step": step,
                "train_condition": "replay" if use_replay else "teacher_forced",
                "train_total": float(total.detach().cpu().item()),
                "eval_total": float(ev_total.detach().cpu().item()),
                "eval_replay_total": float(ev_replay_total.detach().cpu().item()) if ev_replay_total is not None else None,
                "train_losses": s4.summarize_losses(losses),
                "eval_losses": s4.summarize_losses(ev_losses),
                "identity": identity_metrics(ev_out, ev_batch),
                "replay_identity": ev_replay_identity,
                "replay_diagnostics": ev_replay_diag,
                "replay_cache_refresh_count": replay_cache_refresh_count,
                "cuda_max_mem_gb": torch.cuda.max_memory_allocated() / (1024**3) if device.type == "cuda" else 0.0,
                "elapsed_sec": time.time() - started,
            }
            print(json.dumps({"phase": phase, **row}, ensure_ascii=False), flush=True)
            history.append(row)
    with torch.no_grad():
        final, final_losses, final_out, final_batch = forward_loss_stage12(model, ae, fm, fixed_subset, device, args=args, sampling_cfg=sampling_cfg, seed=1207)
        replay_final = None
        replay_final_losses = replay_final_out = replay_final_batch = None
        if args.enable_replay:
            final_cache_entry = None
            if replay_cache:
                final_level = parse_replay_cache_levels(args.replay_cache_levels)[-1][0]
                entries = replay_cache.get(final_level, [])
                if entries:
                    final_cache_entry = entries[0]
            replay_final, replay_final_losses, replay_final_out, replay_final_batch = forward_loss_stage12(
                model,
                ae,
                fm,
                fixed_subset,
                device,
                args=args,
                sampling_cfg=sampling_cfg,
                replay=True,
                seed=2207,
                replay_cache_entry=final_cache_entry,
            )
    initial_value = float(initial.detach().cpu().item())
    final_value = float(final.detach().cpu().item())
    return {
        "phase": phase,
        "steps": steps,
        "batch_size": batch_size,
        "initial_total": initial_value,
        "final_total": final_value,
        "drop_fraction": (initial_value - final_value) / max(abs(initial_value), 1e-8),
        "initial_losses": s4.summarize_losses(initial_losses),
        "final_losses": s4.summarize_losses(final_losses),
        "initial_identity": identity_metrics(initial_out, initial_batch),
        "final_identity": identity_metrics(final_out, final_batch),
        "replay_initial_total": float(replay_initial.detach().cpu().item()) if replay_initial is not None else None,
        "replay_final_total": float(replay_final.detach().cpu().item()) if replay_final is not None else None,
        "replay_final_losses": s4.summarize_losses(replay_final_losses) if replay_final_losses is not None else None,
        "replay_final_identity": identity_metrics(replay_final_out, replay_final_batch) if replay_final_out is not None else None,
        "replay_final_diagnostics": replay_final_batch.get("stage12_replay_diagnostics") if replay_final_batch is not None else None,
        "history": history,
        "trainable": trainable,
        "fixed_replay_cache": {
            "enabled": bool(args.enable_replay and args.enable_fixed_replay_cache),
            "levels": {key: len(value) for key, value in replay_cache.items()},
            "level_spec": args.replay_cache_levels,
            "curriculum_switches": args.replay_curriculum_switches,
            "refresh_every": int(getattr(args, "replay_cache_refresh_every", 0) or 0),
            "refresh_count": replay_cache_refresh_count,
        },
        "elapsed_sec": time.time() - started,
        "step_time_sec": (time.time() - started) / max(steps, 1),
        "cuda_max_mem_gb": torch.cuda.max_memory_allocated() / (1024**3) if device.type == "cuda" else 0.0,
    }


def build_model_stack(device: torch.device, args: argparse.Namespace):
    model, fm, model_meta = s4.build_model(device)
    ckpt_meta = s11.load_strategy_checkpoint(model, args.init_ckpt)
    loss_cfg = configure_stage12_loss(fm, args)
    ae = s5ae.load_autoencoder(args.ae_ckpt, device)
    for p in ae.parameters():
        p.requires_grad = False
    ae.eval()
    return model, fm, ae, model_meta, ckpt_meta, loss_cfg


def parse_args():
    parser = argparse.ArgumentParser(description="Stage12 target-only de-novo multistate training")
    parser.add_argument("--dataset", type=Path, default=DEFAULT_DATASET)
    parser.add_argument("--init-ckpt", type=Path, default=DEFAULT_INIT_CKPT)
    parser.add_argument("--ae-ckpt", type=Path, default=DEFAULT_AE_CKPT)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--run-name", default="stage12_de_novo_multistate")
    parser.add_argument("--seed", type=int, default=1207)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--max-train-samples", type=int, default=161)
    parser.add_argument("--max-val-samples", type=int, default=36)
    parser.add_argument("--overfit1-steps", type=int, default=80)
    parser.add_argument("--overfit4-steps", type=int, default=120)
    parser.add_argument("--pilot-steps", type=int, default=200)
    parser.add_argument("--eval-every", type=int, default=40)
    parser.add_argument("--lambda-ae-seq", type=float, default=1.5)
    parser.add_argument("--lambda-seq-ae-consistency", type=float, default=0.15)
    parser.add_argument("--lambda-flow-gate-reg", type=float, default=0.03)
    parser.add_argument("--ae-seq-hard-state-alpha", type=float, default=0.0)
    parser.add_argument("--ae-seq-hard-state-gamma", type=float, default=0.0)
    parser.add_argument("--target-center-noise-scale-nm", type=float, default=0.20)
    parser.add_argument("--latent-state-residual-noise-scale", type=float, default=0.05)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--skip-training", action="store_true")
    parser.add_argument("--sampling-config", type=Path, default=DEFAULT_SAMPLING_CONFIG)
    parser.add_argument(
        "--enable-teacher-self-conditioning",
        action="store_true",
        default=False,
        help=(
            "Train on teacher-forced x_t_states with model-generated x_sc_states. "
            "This matches original Complexa self-conditioned sampling without using clean binder inputs."
        ),
    )
    parser.add_argument("--teacher-self-cond-prob", type=float, default=1.0)
    parser.add_argument("--enable-replay", action="store_true", default=False)
    parser.add_argument("--replay-mix-prob", type=float, default=0.20)
    parser.add_argument("--replay-warmup-steps", type=int, default=60)
    parser.add_argument("--replay-rollout-steps", type=int, default=6)
    parser.add_argument("--replay-collect-fraction", type=float, default=0.60)
    parser.add_argument("--replay-max-loss-t", type=float, default=0.75)
    parser.add_argument("--replay-teacher-blend", type=float, default=0.0)
    parser.add_argument("--replay-safe-max-bb-ca-distance-nm", type=float, default=0.0)
    parser.add_argument("--replay-safe-max-local-latents-distance", type=float, default=0.0)
    parser.add_argument("--replay-safe-fallback-max-blend", type=float, default=0.85)
    parser.add_argument("--replay-target-shell-max-center-distance-nm", type=float, default=0.0)
    parser.add_argument("--replay-extra-ae-seq-weight", type=float, default=0.75)
    parser.add_argument("--replay-extra-seq-ae-consistency-weight", type=float, default=0.25)
    parser.add_argument("--replay-extra-contact-weight", type=float, default=0.10)
    parser.add_argument("--replay-extra-distance-weight", type=float, default=0.05)
    parser.add_argument("--replay-extra-clash-weight", type=float, default=0.10)
    parser.add_argument(
        "--replay-base-loss-scale",
        type=float,
        default=1.0,
        help=(
            "Scale the original multistate_total on replay batches. Values <1 prevent huge "
            "off-manifold FM losses from drowning AE sequence/manifold repair objectives."
        ),
    )
    parser.add_argument("--enable-fixed-replay-cache", action="store_true", default=False)
    parser.add_argument("--replay-cache-batches", type=int, default=4)
    parser.add_argument(
        "--replay-cache-refresh-every",
        type=int,
        default=0,
        help="If >0, rebuild the fixed replay cache every N training steps using the current model; this implements an online DAgger-style replay curriculum.",
    )
    parser.add_argument(
        "--replay-cache-levels",
        type=str,
        default="easy:0.65,medium:0.35,hard:0.10",
        help="Comma-separated replay curriculum levels as name:teacher_blend.",
    )
    parser.add_argument(
        "--stage13-native-state-path",
        action="store_true",
        default=False,
        help=(
            "Stage13 mode: preserve the checkpoint-compatible native Complexa "
            "target-concat denoiser state-wise, then train multistate shared-sequence/coupling heads on top."
        ),
    )
    parser.add_argument(
        "--stage13-heads-only",
        action="store_true",
        default=False,
        help=(
            "When using Stage13 native-state path, freeze the checkpoint-native "
            "target-conditioned denoiser and train only multistate/shared-sequence heads."
        ),
    )
    parser.add_argument(
        "--stage13-train-latent-repair",
        action="store_true",
        default=False,
        help=(
            "With --stage13-heads-only, additionally train local_latents_linear and "
            "latent sequence repair gates so sampled latents can move back toward the AE sequence manifold."
        ),
    )
    parser.add_argument(
        "--stage14-enable-bounded-latent-repair",
        action="store_true",
        default=False,
        help=(
            "Enable the Stage14 clean-space bounded latent repair path in native-state mode. "
            "The repair is driven by model shared-sequence logits only; true binder sequence remains a loss label."
        ),
    )
    parser.add_argument(
        "--stage14-latent-repair-max-norm",
        type=float,
        default=0.25,
        help="Maximum per-residue clean-space latent residual norm for Stage14 bounded repair.",
    )
    parser.add_argument(
        "--stage14-native-latent-warmup",
        action="store_true",
        default=False,
        help=(
            "Unfreeze the native local_latents_linear and top transformer layers "
            "inside the otherwise frozen native-state path. This targets the "
            "sampled local-latent manifold directly instead of only training readout heads."
        ),
    )
    parser.add_argument(
        "--replay-curriculum-switches",
        type=str,
        default="0.40,0.75",
        help="Progress fractions where replay cache switches to the next difficulty level.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    s4.set_seed(args.seed)
    device = choose_device(args.device)
    samples, manifest = s10.load_dataset(args.dataset)
    train_samples = [s for s in samples if s.get("split") == "train"][: args.max_train_samples]
    val_samples = [s for s in samples if s.get("split") == "val"][: args.max_val_samples]
    if not train_samples:
        raise RuntimeError("No Stage12 train samples selected")
    report_path = REPORT_DIR / f"{args.run_name}_results.json"
    run_dir = RUNS_DIR / args.run_name
    result: dict[str, Any] = {
        "status": "dry_run_passed" if args.dry_run else "running",
        "run_name": args.run_name,
        "device": str(device),
        "dataset": str(args.dataset),
        "train_count": len(train_samples),
        "val_count": len(val_samples),
        "contract": {
            "de_novo_multistate_mode": True,
            "forbidden_model_input_keys": FORBIDDEN_MODEL_INPUT_KEYS,
            "true_binder_sequence_allowed_only_as_loss_label": True,
            "bb_ca_flow_enabled": True,
            "local_latents_flow_enabled": True,
            "stage13_native_state_path": bool(args.stage13_native_state_path),
            "stage13_native_state_path_role": (
                "Preserves the original Complexa target-conditioned generator state-wise; "
                "multistate training should improve shared-sequence/cross-state coupling without replacing the base flow."
            ),
            "stage13_heads_only": bool(args.stage13_heads_only),
            "stage13_train_latent_repair": bool(args.stage13_train_latent_repair),
            "stage14_enable_bounded_latent_repair": bool(args.stage14_enable_bounded_latent_repair),
            "stage14_latent_repair_max_norm": float(args.stage14_latent_repair_max_norm),
            "stage14_native_latent_warmup": bool(args.stage14_native_latent_warmup),
        },
        "manifest_summary": {k: v for k, v in manifest.items() if k != "samples"},
        "training": {},
    }
    if args.dry_run:
        write_json(report_path, result)
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return
    model, fm, ae, model_meta, ckpt_meta, loss_cfg = build_model_stack(device, args)
    sampling_cfg = load_sampling_cfg(args.sampling_config)
    result.update({"model_meta": model_meta, "init_ckpt_meta": ckpt_meta, "stage12_loss_cfg": loss_cfg})
    result["stage15_teacher_self_conditioning"] = {
        "enabled": bool(args.enable_teacher_self_conditioning),
        "prob": float(args.teacher_self_cond_prob),
        "scientific_role": "Expose training to model-generated clean self-conditioning used during de-novo sampling without source-pose or sequence leakage.",
    }
    result["stage12c_replay"] = {
        "enabled": bool(args.enable_replay),
        "mix_prob": args.replay_mix_prob,
        "rollout_steps": args.replay_rollout_steps,
        "collect_fraction": args.replay_collect_fraction,
        "warmup_steps": args.replay_warmup_steps,
        "max_loss_t": args.replay_max_loss_t,
        "teacher_blend": args.replay_teacher_blend,
        "safe_max_bb_ca_distance_nm": args.replay_safe_max_bb_ca_distance_nm,
        "safe_max_local_latents_distance": args.replay_safe_max_local_latents_distance,
        "safe_fallback_max_blend": args.replay_safe_fallback_max_blend,
        "target_shell_max_center_distance_nm": args.replay_target_shell_max_center_distance_nm,
        "fixed_cache_enabled": bool(args.enable_fixed_replay_cache),
        "fixed_cache_batches": args.replay_cache_batches,
        "fixed_cache_refresh_every": args.replay_cache_refresh_every,
        "fixed_cache_levels": args.replay_cache_levels,
        "fixed_cache_curriculum_switches": args.replay_curriculum_switches,
        "sampling_config": str(args.sampling_config),
        "extra_weights": {
            "ae_seq": args.replay_extra_ae_seq_weight,
            "seq_ae_consistency": args.replay_extra_seq_ae_consistency_weight,
            "contact": args.replay_extra_contact_weight,
            "distance": args.replay_extra_distance_weight,
            "clash": args.replay_extra_clash_weight,
            "base_loss_scale": args.replay_base_loss_scale,
        },
    }
    with torch.no_grad():
        probe_total, probe_losses, probe_out, probe_batch = forward_loss_stage12(model, ae, fm, train_samples[: min(2, len(train_samples))], device, args=args, sampling_cfg=sampling_cfg)
        replay_probe = None
        if args.enable_replay:
            replay_probe_total, replay_probe_losses, replay_probe_out, replay_probe_batch = forward_loss_stage12(
                model, ae, fm, train_samples[: min(2, len(train_samples))], device, args=args, sampling_cfg=sampling_cfg, replay=True
            )
            replay_probe = {
                "total": float(replay_probe_total.detach().cpu().item()),
                "losses": s4.summarize_losses(replay_probe_losses),
                "identity": identity_metrics(replay_probe_out, replay_probe_batch),
                "diagnostics": replay_probe_batch.get("stage12_replay_diagnostics"),
            }
    result["probes"] = {
        "initial_total": float(probe_total.detach().cpu().item()),
        "losses": s4.summarize_losses(probe_losses),
        "identity": identity_metrics(probe_out, probe_batch),
        "teacher_self_conditioning_diagnostics": probe_batch.get("stage15_teacher_self_conditioning_diagnostics"),
        "replay": replay_probe,
    }
    write_json(report_path, result)
    if not args.skip_training:
        result["training"]["overfit1"] = run_loop(model, ae, fm, train_samples[:1], device, "overfit", args.overfit1_steps, 1, 2e-4, args.eval_every, args, sampling_cfg)
        model, fm, ae, _, _, _ = build_model_stack(device, args)
        result["training"]["overfit4"] = run_loop(model, ae, fm, train_samples[: min(4, len(train_samples))], device, "overfit", args.overfit4_steps, min(4, args.batch_size), 1e-4, args.eval_every, args, sampling_cfg)
        model, fm, ae, _, _, _ = build_model_stack(device, args)
        batch_size = min(args.batch_size, len(train_samples))
        try:
            result["training"]["pilot"] = run_loop(model, ae, fm, train_samples, device, "pilot", args.pilot_steps, batch_size, 5e-5, args.eval_every, args, sampling_cfg)
        except RuntimeError as exc:
            if "out of memory" not in str(exc).lower() or batch_size <= 1:
                raise
            torch.cuda.empty_cache()
            batch_size = 2 if batch_size > 2 else 1
            result.setdefault("fallbacks", []).append({"reason": "oom", "retry_batch_size": batch_size})
            model, fm, ae, _, _, _ = build_model_stack(device, args)
            result["training"]["pilot"] = run_loop(model, ae, fm, train_samples, device, "pilot", args.pilot_steps, batch_size, 5e-5, args.eval_every, args, sampling_cfg)
        run_dir.mkdir(parents=True, exist_ok=True)
        ckpt_path = run_dir / "stage12_pilot_final.pt"
        torch.save({"model_state_dict": model.state_dict(), "args": vars(args), "run_name": args.run_name}, ckpt_path)
        result["checkpoint_path"] = str(ckpt_path)
        if val_samples:
            with torch.no_grad():
                val_total, val_losses, val_out, val_batch = forward_loss_stage12(model, ae, fm, val_samples[: min(batch_size, len(val_samples))], device, args=args, sampling_cfg=sampling_cfg, seed=888)
                val_replay = None
                if args.enable_replay:
                    val_cache = None
                    if args.enable_fixed_replay_cache:
                        val_cache = build_fixed_replay_cache(
                            model,
                            fm,
                            val_samples[: min(batch_size, len(val_samples))],
                            device,
                            args,
                            sampling_cfg,
                            min(batch_size, len(val_samples)),
                        )
                    val_cache_entry = None
                    if val_cache:
                        final_level = parse_replay_cache_levels(args.replay_cache_levels)[-1][0]
                        entries = val_cache.get(final_level, [])
                        if entries:
                            val_cache_entry = entries[0]
                    val_replay_total, val_replay_losses, val_replay_out, val_replay_batch = forward_loss_stage12(
                        model,
                        ae,
                        fm,
                        val_samples[: min(batch_size, len(val_samples))],
                        device,
                        args=args,
                        sampling_cfg=sampling_cfg,
                        replay=True,
                        seed=889,
                        replay_cache_entry=val_cache_entry,
                    )
                    val_replay = {
                        "total": float(val_replay_total.detach().cpu().item()),
                        "losses": s4.summarize_losses(val_replay_losses),
                        "identity": identity_metrics(val_replay_out, val_replay_batch),
                        "diagnostics": val_replay_batch.get("stage12_replay_diagnostics"),
                    }
            result["validation"] = {
                "total": float(val_total.detach().cpu().item()),
                "losses": s4.summarize_losses(val_losses),
                "identity": identity_metrics(val_out, val_batch),
                "replay": val_replay,
            }
    result["status"] = "passed"
    write_json(report_path, result)
    print(json.dumps({"status": "passed", "report": str(report_path)}, ensure_ascii=False, indent=2), flush=True)


if __name__ == "__main__":
    main()
